# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CICD Example Pipeline

on:
  push:
    branches: ["main"] # You should change this to the branch you want to run the pipeline on if you're testing on a different branch
  pull_request:
    branches: ["main"] # Change this to main if you want to run the pipeline only on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Check formatting with black
        run: |
          pip install black
          black --check src --exclude '.*(test|\.ipynb).*'

      - name: Install service1 dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black pytest
          cd service/service1
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Test all services with pytest
        run: |
          pytest
